/**
 * @file ゲームイベント定義
 * システム間の通信に使用されるイベントを定義します。
 */

/**
 * @enum {Object} GameEvents
 * @description ゲーム内で発生する全イベントを定義します。
 */
export const GameEvents = {
    // --- ゲームフローイベント ---
    GAME_START_CONFIRMED: 'GAME_START_CONFIRMED',
    RESET_BUTTON_CLICKED: 'RESET_BUTTON_CLICKED',
    GAME_WILL_RESET: 'GAME_WILL_RESET',
    BATTLE_INITIALIZED: 'BATTLE_INITIALIZED',
    BATTLE_START_CANCELLED: 'BATTLE_START_CANCELLED',
    BATTLE_START_CONFIRMED: 'BATTLE_START_CONFIRMED',
    SHOW_BATTLE_START_ANIMATION: 'SHOW_BATTLE_START_ANIMATION',
    GAME_PAUSED: 'GAME_PAUSED',
    GAME_RESUMED: 'GAME_RESUMED',
	STRATEGY_EXECUTED: 'STRATEGY_EXECUTED',
	
	// --- プレイヤー入力 & AIイベント ---
    PLAYER_INPUT_REQUIRED: 'PLAYER_INPUT_REQUIRED',
    PART_SELECTED: 'PART_SELECTED',
    AI_ACTION_REQUIRED: 'AI_ACTION_REQUIRED',
    ACTION_SELECTED: 'ACTION_SELECTED',

    // --- BattleSequenceSystem 制御用イベント ---
    // 旧 REQUEST_ACTION_SEQUENCE_START, REQUEST_ACTION_RESOLUTION, ACTION_RESOLUTION_COMPLETED は廃止

    /**
     * アクション実行アニメーションの開始を要求 (BattleSequenceSystem -> ViewSystem (経由なし))
     * ※元々は ActionExecutionSystem -> ViewSystem でしたが、BattleSequenceSystemから直接発行に変更
     * @event EXECUTE_ATTACK_ANIMATION
     */
    EXECUTE_ATTACK_ANIMATION: 'EXECUTE_ATTACK_ANIMATION',

    /**
     * アクション実行アニメーションの完了 (ViewSystem -> BattleSequenceSystem)
     * @event EXECUTION_ANIMATION_COMPLETED
     */
    EXECUTION_ANIMATION_COMPLETED: 'EXECUTION_ANIMATION_COMPLETED',

    /**
     * 結果表示要求 (BattleSequenceSystem -> MessageSystem)
     * @event REQUEST_RESULT_DISPLAY
     */
    REQUEST_RESULT_DISPLAY: 'REQUEST_RESULT_DISPLAY',

    /**
     * クールダウン移行要求 (BattleSequenceSystem -> CooldownSystem)
     * @event REQUEST_COOLDOWN_TRANSITION
     */
    REQUEST_COOLDOWN_TRANSITION: 'REQUEST_COOLDOWN_TRANSITION',

    /**
     * クールダウン移行完了 (CooldownSystem -> BattleSequenceSystem)
     * @event COOLDOWN_TRANSITION_COMPLETED
     */
    COOLDOWN_TRANSITION_COMPLETED: 'COOLDOWN_TRANSITION_COMPLETED',

    /**
     * アクションシーケンス全体の完了
     * @event ACTION_SEQUENCE_COMPLETED
     */
    ACTION_SEQUENCE_COMPLETED: 'ACTION_SEQUENCE_COMPLETED',

    // --- その他イベント ---
    COMBAT_SEQUENCE_RESOLVED: 'COMBAT_SEQUENCE_RESOLVED',
    COMBAT_RESOLUTION_DISPLAYED: 'COMBAT_RESOLUTION_DISPLAYED',
    ACTION_COMPLETED: 'ACTION_COMPLETED',
    ATTACK_DECLARATION_CONFIRMED: 'ATTACK_DECLARATION_CONFIRMED',

    // --- 状態 & ターン管理イベント ---
    ACTION_SELECTION_COMPLETED: 'ACTION_SELECTION_COMPLETED',
    ACTION_EXECUTION_COMPLETED: 'ACTION_EXECUTION_COMPLETED',
    TURN_START: 'TURN_START',
    TURN_END: 'TURN_END',
    GAUGE_FULL: 'GAUGE_FULL',
    ACTION_QUEUE_REQUEST: 'ACTION_QUEUE_REQUEST',
    ACTION_REQUEUE_REQUEST: 'ACTION_REQUEUE_REQUEST',
    NEXT_ACTOR_DETERMINED: 'NEXT_ACTOR_DETERMINED',
    ACTION_CANCELLED: 'ACTION_CANCELLED',
    PART_BROKEN: 'PART_BROKEN',
    PLAYER_BROKEN: 'PLAYER_BROKEN',
    GAME_OVER: 'GAME_OVER',
    HP_UPDATED: 'HP_UPDATED',
    EFFECT_EXPIRED: 'EFFECT_EXPIRED',
    GUARD_BROKEN: 'GUARD_BROKEN',

    // --- UI & Sceneイベント ---
    SCENE_CHANGE_REQUESTED: 'SCENE_CHANGE_REQUESTED',
    SHOW_MODAL: 'SHOW_MODAL',
    HIDE_MODAL: 'HIDE_MODAL',
    MODAL_CLOSED: 'MODAL_CLOSED',
    MODAL_SEQUENCE_COMPLETED: 'MODAL_SEQUENCE_COMPLETED',
    SETUP_UI_REQUESTED: 'SETUP_UI_REQUESTED',
    HP_BAR_ANIMATION_REQUESTED: 'HP_BAR_ANIMATION_REQUESTED',
    HP_BAR_ANIMATION_COMPLETED: 'HP_BAR_ANIMATION_COMPLETED',

    // --- カスタマイズ画面イベント ---
    CUST_CONFIRM_INPUT: 'CUST_CONFIRM_INPUT',
    CUST_CANCEL_INPUT: 'CUST_CANCEL_INPUT',
    CUST_NAVIGATE_INPUT: 'CUST_NAVIGATE_INPUT',
    EQUIP_PART_REQUESTED: 'EQUIP_PART_REQUESTED',
    EQUIP_MEDAL_REQUESTED: 'EQUIP_MEDAL_REQUESTED',
    PART_EQUIPPED: 'PART_EQUIPPED',
    MEDAL_EQUIPPED: 'MEDAL_EQUIPPED',
    CUSTOMIZE_EXIT_REQUESTED: 'CUSTOMIZE_EXIT_REQUESTED',
    CUSTOMIZE_SCENE_REQUESTED: 'CUSTOMIZE_SCENE_REQUESTED',

    // --- マップ画面イベント ---
    INTERACTION_KEY_PRESSED: 'INTERACTION_KEY_PRESSED',
    NPC_INTERACTION_REQUESTED: 'NPC_INTERACTION_REQUESTED',
    NPC_INTERACTED: 'NPC_INTERACTED',
    MENU_TOGGLE_REQUESTED: 'MENU_TOGGLE_REQUESTED',
    GAME_SAVE_REQUESTED: 'GAME_SAVE_REQUESTED',
    UI_STATE_CHANGED: 'UI_STATE_CHANGED',
};